name: CI

on:
  push:
    branches: 
      - Alejandro
  pull_request:
    branches: 
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build and test Docker image
      run: |
        docker build -t myapp .
        docker run myapp dotnet test
